name: S3 DevSecOps Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    #CHECKOUT CODE
    steps:
      - name: Checkout
        uses: actions/checkout@v4

    #SONAR CLOUD CONFIGURE
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=vigneshk0101_s3first
            -Dsonar.organization=vigneshk0101
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

    #INSTALLING TOOLS
      - name: Install Trivy #1
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

          wget https://github.com/aquasecurity/trivy/releases/download/v0.69.3/trivy_0.69.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.69.3_Linux-64bit.deb

      - name: Install Gitleaks #2
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

    #RUNNING SCANS
      - name: Export SonarCloud Report #1
        run: |
          curl -u "${{ secrets.SONAR_TOKEN }}:" \
          "https://sonarcloud.io/api/issues/search?componentKeys=vigneshk0101_s3first" \
          -o sonar-report.json
          
      - name: Run Trivy Scan #2
        run: |
          trivy fs . --format json --output trivy-report.json

      - name: Run Gitleaks #3
        run: |
          gitleaks detect --source . --report-format sarif --report-path gitleaks-report.sarif

    #CONFIGURE AWS
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


    #REMEDIATION SCRIPT RUNNING
      - name: Run S3 Auto-Remediation
        run: |
          chmod +x scripts/remediate.sh
          ./scripts/remediate.sh

    #UPLOAD REPORTS TO S3
  
      - name: Upload Reports to S3
        if: always()
        run: |
          TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)

          aws s3 cp gitleaks-report.sarif s3://s3first-project-all-files/reports/$TIMESTAMP/ || true
          aws s3 cp trivy-report.json s3://s3first-project-all-files/reports/$TIMESTAMP/ || true
          aws s3 cp sonar-report.json s3://s3first-project-all-files/reports/$TIMESTAMP/ || true